pentaho-bi.base-url=https://bi.sep.es.gov.br
pentaho-bi.user-id=${PENTAHO_BI_USER_ID:${pentahoBI.userId:}}
pentaho-bi.password=${PENTAHO_BI_PASSWORD:${pentahoBI.password:}}

pentaho-bi.cooperation-years-path=/public/dashboard/pmo/dados_abertos/dados_abertos_conv_ano.cda
pentaho-bi.cooperation-years-data-access-id=dados_abertos_conv_ano
pentaho-bi.cooperation-organizations-path=/public/dashboard/pmo/dados_abertos/dados_abertos_conv_orgao.cda
pentaho-bi.cooperation-organizations-data-access-id=dados_abertos_conv_orgao
pentaho-bi.cooperation-processes-path=/public/dashboard/pmo/dados_abertos/dados_abertos_conv_processos.cda
pentaho-bi.cooperation-processes-data-access-id=dados_abertos_conv_processos

pentaho-bi.contract-years-path=/public/dashboard/pmo/dados_abertos/dados_abertos_contr_ano.cda
pentaho-bi.contract-years-data-access-id=dados_abertos_contr_ano
pentaho-bi.contract-organizations-path=/public/dashboard/pmo/dados_abertos/dados_abertos_contr_orgao.cda
pentaho-bi.contract-organizations-data-access-id=dados_abertos_contr_orgao
pentaho-bi.contract-processes-path=/public/dashboard/pmo/dados_abertos/dados_abertos_contr_processos.cda
pentaho-bi.contract-processes-data-access-id=dados_abertos_contr_processos
